--ALTER TABLE Products DISABLE CHANGE_TRACKING;
--ALTER DATABASE SyncTest SET CHANGE_TRACKING = OFF;

USE AzureSearchSyncTest
go

ALTER DATABASE AzureSearchSyncTest
SET CHANGE_TRACKING = ON
(CHANGE_RETENTION = 2 DAYS, AUTO_CLEANUP = ON);
go

ALTER TABLE Products
ENABLE CHANGE_TRACKING
WITH (TRACK_COLUMNS_UPDATED = OFF);
go
